// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['bilicomicdownloader']['Config']['GetConfig']();
}

export function Save() {
  return window['go']['bilicomicdownloader']['Config']['Save']();
}

export function SaveConfig(arg1) {
  return window['go']['bilicomicdownloader']['Config']['SaveConfig'](arg1);
}
