// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearDownloaders() {
  return window['go']['bilicomicdownloader']['DownloaderManager']['ClearDownloaders']();
}

export function DownloadList(arg1) {
  return window['go']['bilicomicdownloader']['DownloaderManager']['DownloadList'](arg1);
}

export function GetBookInfo() {
  return window['go']['bilicomicdownloader']['DownloaderManager']['GetBookInfo']();
}

export function GetChapter() {
  return window['go']['bilicomicdownloader']['DownloaderManager']['GetChapter']();
}

export function GetDownloader(arg1) {
  return window['go']['bilicomicdownloader']['DownloaderManager']['GetDownloader'](arg1);
}

export function GetDownloaders() {
  return window['go']['bilicomicdownloader']['DownloaderManager']['GetDownloaders']();
}

export function ProcessSend() {
  return window['go']['bilicomicdownloader']['DownloaderManager']['ProcessSend']();
}
